theme: jekyll-theme-minimal
title: Clever Girl Studio
description: Fantastic art from a clever girl
# logo: [Location of the logo]
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
